---
- name: install ntp
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp
  notify: restart ntp

- name: copy ntp default conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
